name: qonnect cockpit
favicon: null
layout_spectrum: 0.7569877298083156
typography_spectrum: 0.23876930982805789
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  brandStrength: 0.9477855456061661
  lightness: 0.6188415556680411
  saturation: 0.8639030328486115
  rhythmicContrast: 0.1358329791110009
purpose: []
