name: qonnect cockpit
favicon: null
layout_spectrum: 1
typography_spectrum: 0.23876930982805789
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fafafa'
    - '#858585'
    - '#0a0a0a'
    - '#3d3d3d'
    - '#bababa'
  brandStrength: 0.5
  lightness: 0.6188415556680411
  saturation: 0.8639030328486115
  rhythmicContrast: 0.25
purpose: []
