name: qonnect cockpit
favicon: null
layout_spectrum: 1
typography_spectrum: 0.23876930982805789
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#6dc497'
    - '#ffffff'
    - '#4d4d4d'
    - '#141414'
    - '#d879ab'
  brandStrength: 0.5
  lightness: 0.6188415556680411
  saturation: 0.8639030328486115
  rhythmicContrast: 0.25
purpose: []
